# IMPORTANT NOTES: 
# 1. DO NOT DELETE ANY ROW
# 2. DO NOT ADD ANY ROW
# 3. ONLY CHANGE THE VALUES AFTER THE = (EQUALS) SIGN
# 4. READ THE NOTE ABOVE EVERY KEY-VALUE PAIR. WHERE THERE IS A CONSTRAINT ON WHAT VALUES THE KEY CAN TAKE, ENSURE THAT ONLY THOSE VALUES ARE PUT.
# 5. AFTER A VALUE IS PUT, UNLESS OTHERWISE SPECIFIED, ENSURE THAT THERE IS NO SPACE AFTER THE VALUE
# 6. IF THERE IS ANY DEVIATION FROM THE ABOVE RULES, THE RESULTS WILL BE FLAKY

# The input folder where images come from the camera
# input.folder=D:/130052-TTK_VISION/VISION/Common
input.folder=E:/TechWerx/Java/Working/Input

# The change in directory contents triggers immediately, but the incoming image file transfer takes more time
# So, we have to wait and poll to check if the image has received any further bytes from the camera
# This polling time is in milliseconds
polling.time=5

# The folder where the price master csv is located
# pricemaster.folder=D:/130052-TTK_VISION/VISION/Common/Price Master
pricemaster.folder=E:/TechWerx/Java/Working/Input/Price Master

# The actual name of the price master csv
# pricemaster.file=Price master summary.csv

# The folder where the processed images are moved
# output.folder=D:/130052-TTK_VISION/VISION/Common/Processed Images
output.folder=E:/TechWerx/Java/Working/Output

# The folder where the results are published. If the image is 1.txt, the result file is 1.txt
# If the image file is 2 (1).png, the result file is 2 (1).txt
# results.folder=D:/130052-TTK_VISION/VISION/Common/Response
results.folder=E:/TechWerx/Java/Working/Output/Results

# Does the pricemaster have a header i.e. whether the first line is a header or starts directly with product information
pricemaster.header=yes

# The minimum height required for the price
price.minimumheight=9

# The minimum height required for the date
date.minimumheight=9

# The minimum spacing required for the 1st and 2nd price digits as a multiple of the other gaps
spacing.minimummultipleofgaps=1.5

# The minimum spacing required for the 1st and 2nd price digits as a multiple of the width of the other charcaters
# We need both this and the previous one, because sometimes it is possible to identify only one of them
spacing.minimummultipleofchars=0.6

# Which months are allowed. Values can be only 'current' or 'all'. Current allows both current and previous month.
# The code logic works for December as well, where the year allowed includes the previous year as well
months.allowed=all

# The error phrase to be printed if a .00 is not found in price. Note the space at the end of the string
pricedot.error=.00 not found. 

# The error phrase to be printed if month cannot be found. Note the space at the end of the string
month.error=Error in printing month. 

# The error phrase to be printed if year cannot be found. Note the space at the end of the string
year.error=Error in printing year. 

# The error phrase to be printed if product cannot be found. Note the space at the end of the string
product.error=Error in printing product. 

# The error phrase to be printed if price cannot be found. Note the space at the end of the string
price.error=Error in printing price. 

# The error phrase to be printed if price height is less than minimum required. Note the space at the end of the string
priceheight.error=Price height is %.1f mm, which is less than minimum of %.1f mm. 

# The error phrase to be printed if date and month height is less than minimum required. Note the space at the end of the string
dateandmonthheight.error=Month and year height is %.1f mm, which is less than minimum of %.1f mm. 

# The error phrase to be printed if spacing between 1st and 2nd price digits is less than a certain multiple of the rest of the digits. Note the space at the end of the string
pricespacingwidth.error=Spacing is %.1f mm, which is less than %.1f mm (= %.1f * average width of the rest of the digits). 

# The error phrase to be printed if spacing between 1st and 2nd price digits is less than a certain multiple of the gap between the other digits. Note the space at the end of the string
pricespacinggap.error=Spacing is %.1f mm, which is less than %.1f mm, the average gap between the rest of the digits. 

# If both spacings should be ok, then value = both; else, value = any
needed.pricespacingsok=any

# Report automatically after every WatchDirectory cycle completes. Values are false or true. Note that a value of false does not disable the Report Stats button
auto.report=false

# Run in GUI mode or background mode. Valid values are 'gui' or 'background'
run.mode=gui

# DO NOT CHANGE THESE VALUES UNDER ANY CIRCUMSTANCES 
# -----------------------------------------------------
# The folder where the Leptonica and Tesseract libraries are present. 
# Remember that (tess4j/win32-x86-64 & lept4j/win32-x86-64) OR (tess4j/win32-x86 & lept4j/win32-x86) will be added to the folder
# libtesseract410.dll and liblept1780.dll need to be in the respective folders D:/130052-TTK_VISION/VISION/Common/External/tess4j/win32-x86-64 and 
# D:/130052-TTK_VISION/VISION/Common/External/lept4j/win32-x86-64
# externallib.folder=D:/130052-TTK_VISION/VISION/Common/External
# externallib.folder=C:/Users/Admin/AppData/Local/Temp/
externallib.folder=E:/TechWerx/Java/Working/Input/External Libraries

# Tesseract's datapath; this is where the eng.traineddata file is found
# tesseract.datapath=C:/Program Files/Tesseract-OCR/tessdata
tesseract.datapath=C:/Program Files/Tesseract-OCR/tessdata

# Control whether System.out is seen or not. Values are ignore and activate
# system.out=ignore
system.out=activate

debuggingimages.folder=E:/TechWerx/Java/Working/Output/debuggingImages

# Important constants
ich=21
# ich=15
icw=13
# icw=9
#ich=18
#icw=11
#dl=9
#dl=99
#dl=2